Add item requests
vlsknan/java-shareit pull request #3
Opened 2022-10-17 22:32 UTC by vlsknan

2022-10-19 16:27 UTC, NikolaiDem approved these changes

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
Для выполнения операций с БД лучше добавить транзакции.
Аналогично для всех сервисов.

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> + * TODO Sprint add-item-requests.
TODO лучше использовать для указания, что еще осталось сделать. А здесь все уже готово)
Аналогично для остальных TODO.

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Пользователь с id = {} не найден", userId)));
String.format("Пользователь с id = %s не найден", userId)
Аналогично для остальных.

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (itemRequestDto.getDescription() != null) {
На поле description в ItemRequestDto можно навесить аннотацию @NotEmpty и избавиться от проверки 
if (itemRequestDto.getDescription() != null){}

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +            "order by r.id desc")
Сортировать лучше по дате создания, так как может поменяться алгоритм генерации id, например.

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        return itemRequestRepository.findAll(PageRequest.of(page, size)).stream()
И еще в PageRequest добавить сортировку по дате создания.

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .filter(itemRequest -> !Objects.equals(itemRequest.getRequester().getId(), requester.getId()))
(Optional)
Исключить текущего пользователя можно на уровне запроса в БД.

2022-10-19 16:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        final PageRequest pageRequest = PageRequest.of(page, size, Sort.by(Sort.Direction.ASC, "id"));
Использовать сортировку по дате создания.

2022-10-19 16:37 UTC, NikolaiDem requested changes
Откат предыдущего аппрува)

2022-10-19 21:42 UTC, vlsknan commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        final PageRequest pageRequest = PageRequest.of(page, size, Sort.by(Sort.Direction.ASC, "id"));
Но ведь у item нет даты создания. У booking и request сделала по дате начала бронирования и по дате создания запроса.

2022-10-20 23:20 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        final PageRequest pageRequest = PageRequest.of(page, size, Sort.by(Sort.Direction.ASC, "id"));
Анна, верно, посмотрел не в ту таблицу)

2022-10-20 23:22 UTC, NikolaiDem approved these changes

2022-10-20 23:44 UTC, merged